name: torch-rl

dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - pip
  - ipykernel
  - pip:
    - brax
    - mujoco
    - mujoco-mjx
    - dm_control
    #\- torchrl
    - git+https://github.com/scott-yj-yang/rl.git  # use our modified torchrl fork
    #- git+https://github.com/KevinBian107/torch_rl_vnl.git
    - hydra-core --upgrade
    - moviepy

# Still need to use the following code to enable JAX on CUDA 
# pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
# pip install -U numba

# for headless gpu rendering setup
# sudo apt-get install libglfw3 libglew2.0 libgl1-mesa-glx libosmesa6
# conda install -c conda-forge glew
# conda install -c conda-forge mesalib
# conda install -c anaconda mesa-libgl-cos6-x86_64
# conda install -c menpo glfw3

# conda env config vars set MUJOCO_GL=egl PYOPENGL_PLATFORM=egl
# conda deactivate && conda activate base